// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtgux8ckYJ3hbnWlr0I9fumepimDTX6a0',
    appId: '1:29978125325:web:6ced85eea48ac83d22e144',
    messagingSenderId: '29978125325',
    projectId: 'simplechat-4880e',
    authDomain: 'simplechat-4880e.firebaseapp.com',
    databaseURL: 'https://simplechat-4880e-default-rtdb.firebaseio.com',
    storageBucket: 'simplechat-4880e.firebasestorage.app',
    measurementId: 'G-NRNCXH8B5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNu9XXGdPuEuhXxH9aax07IEMJ73tE-bg',
    appId: '1:29978125325:android:cc4748dd5f74745a22e144',
    messagingSenderId: '29978125325',
    projectId: 'simplechat-4880e',
    databaseURL: 'https://simplechat-4880e-default-rtdb.firebaseio.com',
    storageBucket: 'simplechat-4880e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtgux8ckYJ3hbnWlr0I9fumepimDTX6a0',
    appId: '1:29978125325:web:fb49dc4bd09a110622e144',
    messagingSenderId: '29978125325',
    projectId: 'simplechat-4880e',
    authDomain: 'simplechat-4880e.firebaseapp.com',
    databaseURL: 'https://simplechat-4880e-default-rtdb.firebaseio.com',
    storageBucket: 'simplechat-4880e.firebasestorage.app',
    measurementId: 'G-ZFD1Y6YBDT',
  );

}